
GET http://localhost:8080/api/quiz?idMateria=2




POST http://localhost:8080/api/quiz
Content-Type: application/json
{
  "materiaId": 2,
  "materia": "React",
  "difficulty": 2,
  "numQuestions": 10,
  "help": true
}







